language: node_js
node_js: lts/*
sudo: false

cache:
  yarn: true
install: true
script: echo "script"
before_deploy:
  - npm install
  - npm run build
  - ls -l
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1/GfYwS4BoeNYNrDosglzoSpKOQKo_EGM57eVyE4LSJKGzWJWpSuot3WDtZ4xaKfx2"